server:
  port: 9000
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          basic-client:
            registration:
              client-id: "football"
              client-secret: "{noop}SuperSecret"
              client-authentication-methods:
                - "client_secret_post"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "football:read"